/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "AppWindow.h"


//==============================================================================
class DrumLooperApplication  : public JUCEApplication
{
public:
    //==============================================================================
    DrumLooperApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return true; }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        appWindow = new AppWindow();
        appWindow->centreWithSize(700, 615);
        appWindow->setVisible(true);
    }

    void shutdown()
    {
        
        //std::cout << "main shutdown reached\n";
        
        deleteAndZero (appWindow);
        //delete appWindow;
        
        //std::cout << "main shutdown reached - app window deleted\n";
        
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }
    
private:
    AppWindow* appWindow;
    //ScopedPointer<AppWindow> appWindow;
    
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (DrumLooperApplication)
